# Generated by Django 3.2.3 on 2021-05-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
