# Generated by Django 3.2.3 on 2021-05-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Расходы на ремонт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='machine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель машинки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='malfunction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Неисправность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='summ',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Сумма за ремонт'),
        ),
    ]
