# Generated by Django 3.2.3 on 2021-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210514_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_img/', verbose_name='Главное фото')),
                ('title', models.CharField(max_length=255, verbose_name='Главный заголовок')),
            ],
        ),
    ]
