# Generated by Django 3.2.3 on 2021-05-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='malfunction',
            field=models.CharField(blank=True, choices=[('Диагностика', 'Диагностика'), ('Модуль управления', 'Модуль управления'), ('Не нагревает воду', 'Не нагревает воду'), ('Ремонт электродвигателя', 'Ремонт электродвигателя'), ('Не сливает воду', 'Не сливает воду'), ('Не набирает воду', 'Не набирает воду'), ('Утечка воды', 'Утечка воды'), ('Не крутит барабан', 'Не крутит барабан'), ('Устранение засора', 'Устранение засора'), ('Установка', 'Установка'), ('Не включается', 'Не включается'), ('Прочие неисправности', 'Прочие неисправности')], max_length=255, null=True, verbose_name='Неисправность'),
        ),
    ]
