# Generated by Django 3.2.3 on 2021-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_order_malfunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='malfunction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Неисправность'),
        ),
    ]
